# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-04 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_level', models.CharField(max_length=15)),
                ('geo_code', models.CharField(max_length=10)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('long_name', models.CharField(db_index=True, max_length=100, null=True)),
                ('square_kms', models.FloatField(null=True)),
                ('parent_level', models.CharField(max_length=15, null=True)),
                ('parent_code', models.CharField(max_length=10, null=True)),
                ('province_name', models.CharField(max_length=100)),
                ('province_code', models.CharField(max_length=5)),
                ('category', models.CharField(max_length=2)),
                ('miif_category', models.TextField(null=True)),
                ('population', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='geography',
            unique_together=set([('geo_level', 'geo_code')]),
        ),
    ]
