# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-04 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[(b'Planned', b'Planned'), (b'Preparation', b'In preparation'), (b'Implementation', b'Implementation'), (b'Closing', b'Documentation & Closing')], max_length=255)),
                ('area_of_work', models.CharField(blank=True, max_length=255)),
                ('mode_of_delivery', models.CharField(blank=True, max_length=255)),
                ('partner', models.CharField(blank=True, max_length=255)),
                ('agenda', models.CharField(blank=True, max_length=255)),
                ('m_and_e', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scorecard.Geography')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scorecard.Programme')),
            ],
        ),
    ]
