# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-03 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0002_geography_development_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_level', models.CharField(max_length=15)),
                ('geo_code', models.CharField(max_length=10)),
                ('programme', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[(b'Planned', b'Planned'), (b'Preparation', b'In preparation'), (b'Implementation', b'Implementation'), (b'Closing', b'Documentation & Closing')], max_length=255)),
                ('area_of_work', models.CharField(blank=True, max_length=255)),
                ('mode_of_delivery', models.CharField(blank=True, max_length=255)),
                ('partner', models.CharField(blank=True, max_length=255)),
                ('agenda', models.CharField(blank=True, max_length=255)),
                ('m_and_e', models.CharField(blank=True, max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
            ],
        ),
        #migrations.RemoveField(
        #    model_name='geography',
        #    name='year',
        #),
        #migrations.AddField(
        #    model_name='geography',
        #    name='population',
        #    field=models.IntegerField(null=True),
        #),
    ]
