# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-10 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0003_auto_20181204_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='agenda',
            new_name='supported_policies',
        ),
    ]
