# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-03 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0004_auto_20181203_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='geo_level',
        ),
    ]
