# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-24 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0004_auto_20181210_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geography',
            options={'verbose_name_plural': 'geographies'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='email',
        ),
    ]
