# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-03 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorecard', '0005_auto_20181203_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='geo_code',
            new_name='geo',
        ),
    ]
